### ISSUE TITLE
Implement fetching balance and previous transactions [0.5 XMR]

### ISSUE THREAD

**Issue by detherminal** [monumexyz/libmonero#2]
Implement fetching or calculating balance and previous transactions from nodes without extracting the private spend key from device. You should complete the functions described in wallet.go file. The first person to get merged a pr with a appropriate solution gets the bounty of 0.5 XMR.

Bounty:
- 0.20 XMR: Getting balance
- 0.30 XMR: Getting previous transactions

**Comment by WaffleManEaters** [comment]
I started this bounty

**Comment by detherminal** [comment]
> I started this bounty

Got it. You need to do it without running a daemon or wallet rpc locally. It should be remote public node. It can either be [local or remote synchronization](https://www.getmonero.org/downloads/) as described in the given pages bottom third party wallets section.

Hope it goes well.

**Comment by WaffleManEaters** [comment]
I'm no longer working on this

**Comment by Justxd22** [comment]
here's the workflow that needs to be implemented

1. get wallet height 
   - either from user input
   - or use latest block height

2. use /get_info rpc method to get current latest block height

3. make progress function
   - current height - target height
   - ptc = diff <= 0 ? 0.0 : diff / track; //precent

4. make a loop to go over blocks untill latest height
   - try to decode transactions in every block using wallet view key
     - if success try to get amount and balance += amount

something like (in go)

```python
from monerorpc.authproxy import AuthServiceProxy, JSONRPCException

# Connect to Monero node's JSON-RPC interface
rpc_url = "http://xmr-node.cakewallet.com:18081/json_rpc"
rpc = AuthServiceProxy(rpc_url)

def scan_transactions(wallet_address, public_view_key):
    latest_block_height = rpc.get_height()['height']

    for height in range(latest_block_height, 0, -1):
        block = rpc.get_block(height)
        transactions = block['tx_hashes']

        for tx_hash in transactions:
            try:
                tx = rpc.get_transaction(tx_hash)
                
                # Decode the transaction using the public view key
                decoded_tx = rpc.decode_outputs(tx['as_hex'], public_view_key)
                
                for output in decoded_tx['vout']:
                    if wallet_address in output['target']['data']:
                        # Process the transaction and update wallet balance
                        pass
            except JSONRPCException as e:
                # Handle exception, for example, transaction decoding failure
                pass

wallet_address = "your_wallet_address"
public_view_key = "your_public_view_key"
scan_transactions(wallet_address, public_view_key)
```




here's the rpc methods to be used

- current height
```bash
curl http://xmr-node.cakewallet.com:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_info"}' -H 'Content-Type: application/json'
```
- get blocks
```bash
curl http://xmr-node.cakewallet.com:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_block","params":{"height":2901405}}' -H 'Content-Type: application/json'
```

- get transactions using tx_hash
```bash
curl http://xmr-node.cakewallet.com:18081/gettransactions --data '{"prune": true, "decode_as_json": false, "txs_hashes":["d6e48158472848e6687173a91ae6eebfa3e1d778e65252ee99d7515d63090408"]}'  -H 'Content-Type: application/json'
```

need to find and implement the decode functions in go
