### ISSUE TITLE
Add transfering (sending) functionality [0.5 XMR]

### ISSUE THREAD

**Issue by detherminal** [monumexyz/libmonero#3]
Make a transaction and sign it with the given private key, then broadcast the signed transaction to the node. The first person to get merged a pr with a appropriate solution gets the bounty of 0.5 XMR.

Bounty:
- 0.5 XMR: Adding transfer functionality

**Comment by Justxd22** [comment]
Hello @detherminal,

How do you wanna do this? We can use the monero bin like monero-wallet-cli I've done similar thing in python to send/receive xmr from python api 

https://github.com/Justxd22/monero-wallet-cli-wrapper

**Comment by Justxd22** [comment]
The project attached in python scans wallet from seed finds balance and sweeps to a target address

**Comment by detherminal** [comment]
> Hello @detherminal,
> 
> How do you wanna do this? We can use the monero bin like monero-wallet-cli I've done similar thing in python to send/receive xmr from python api 
> 
> https://github.com/Justxd22/monero-wallet-cli-wrapper

It should sign the transaction in pure golang and broadcast it via a public node. There shouldnt be a need for any binary.

**Comment by Justxd22** [comment]
> > Hello @detherminal,
> > 
> > How do you wanna do this? We can use the monero bin like monero-wallet-cli I've done similar thing in python to send/receive xmr from python api 
> > 
> > https://github.com/Justxd22/monero-wallet-cli-wrapper
> 
> It should sign the transaction in pure golang and broadcast it via a public node. There shouldnt be a need for any binary.


Done via the JSON-RPC API, right?

**Comment by detherminal** [comment]
Yes, should be with json rpc if used via public remote node.

**Comment by Justxd22** [comment]
@detherminal ok, can i mark this bounty as started

**Comment by detherminal** [comment]
There is no need to mark it, I know that you started, I will give the bounty to you if you complete it earlier than anyone else.

**Comment by Justxd22** [comment]
@detherminal any public rpc to test ??

**Comment by Justxd22** [comment]
I've a question how do you wanna use public node and make transactions/view balance? I just checked out cake wallet public rpc node they don't allow wallet restore from seed 

`https://xmr-node.cakewallet.com:18081/json_rpc`


This can be done via a local rpc node and while configuring it you can use the option 

`-wallet-dir your_wallet_folder/`


Then you can use the api from Go to view/spend/get balance also create new wallets and use multiple accounts 

Please clarify your request

**Comment by Justxd22** [comment]
I've a question how do you wanna use public node and make transactions/view balance? I just checked out cake wallet public rpc node they don't allow wallet restore from seed 

`https://xmr-node.cakewallet.com:18081/json_rpc`


This can be done via a local rpc node and while configuring it you can use the option 

`-wallet-dir your_wallet_folder/`


Then you can use the api from Go to view/spend/get balance also create new wallets and use multiple accounts 

Please clarify your request

**Comment by detherminal** [comment]
You should use the public remote node to only broadcast the signed transaction. You should sign it locally in pure golang with the given private spend key and broadcast it to the node.

**Comment by Justxd22** [comment]
> You should use the public remote node to only broadcast the signed transaction. You should sign it locally in pure golang with the given private spend key and broadcast it to the node.

I get that, this can be done by syncing blocks from a node and using wallet key to spend/view and scan for transactions, kind of like cake wallet, is that what you're trying to achieve?

Found this docs similar thing done in js

https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/view_only_offline.md

**Comment by detherminal** [comment]
Scanning for transactions is other bounty, this bounty is for adding transfering functionality.
